pipeline {
    agent any

    environment {
        // Tomcat details
        TOMCAT_URL = 'http://api-nec-prod-1587031398.me-central-1.elb.amazonaws.com:8080'
        TOMCAT_APP_NAME = 'user_project' // You can change this to any context name
        // Jenkins credentials ID for Tomcat Manager user
        TOMCAT_CREDENTIALS_ID = 'tomcat-manager-cred' // Replace with your actual credentials ID
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build WAR') {
            agent {
                docker {
                    image 'maven:3.9.6-eclipse-temurin-11'
                    args '-u root'
                    reuseNode true
                }
            }
            steps {
              //  sh 'mvnw clean install -Dmaven.test.skip=true -P docker'
            //}
		dir('deployOne') {
    			sh 'mvn clean install -Dmaven.test.skip=true -P docker'
		   }
		}
        }

        stage('Deploy to Tomcat') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.TOMCAT_CREDENTIALS_ID, usernameVariable: 'TOMCAT_USER', passwordVariable: 'TOMCAT_PASS')]) {
                    script {
                        def warFile = findFiles(glob: 'target/*.war')[0]
                        def deployUrl = "${TOMCAT_URL}/manager/text/deploy?path=/${TOMCAT_APP_NAME}&update=true"
                        sh """
                            curl --fail -v --upload-file ${warFile.path} \\
                                --user $TOMCAT_USER:$TOMCAT_PASS \\
                                '${deployUrl}'
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        success {
            echo 'WAR deployed to Tomcat successfully!'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}

